import React from "react";

export const nsoCardData = [
  {
    LOB: "iPhone",
    CY_Green_POS_Cnt: 44,
    CY_Amber_POS_Cnt: 23,
    CY_Red_POS_Cnt: 32,
    PY_Green_POS_Cnt: 10,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 11,
    PQ_Amber_POS_Cnt: 12,
    PQ_Red_POS_Cnt: 62,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
  {
    LOB: "Watch",
    CY_Green_POS_Cnt: 1,
    CY_Amber_POS_Cnt: 8,
    CY_Red_POS_Cnt: 97,
    PY_Green_POS_Cnt: 0,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 0,
    PQ_Amber_POS_Cnt: 1,
    PQ_Red_POS_Cnt: 91,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
  {
    LOB: "Mac",
    CY_Green_POS_Cnt: 12,
    CY_Amber_POS_Cnt: 23,
    CY_Red_POS_Cnt: 71,
    PY_Green_POS_Cnt: 0,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 0,
    PQ_Amber_POS_Cnt: 3,
    PQ_Red_POS_Cnt: 89,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
  {
    LOB: "iPad",
    CY_Green_POS_Cnt: 15,
    CY_Amber_POS_Cnt: 18,
    CY_Red_POS_Cnt: 79,
    PY_Green_POS_Cnt: 0,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 2,
    PQ_Amber_POS_Cnt: 5,
    PQ_Red_POS_Cnt: 91,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
  {
    LOB: "All",
    CY_Green_POS_Cnt: 28,
    CY_Amber_POS_Cnt: 20,
    CY_Red_POS_Cnt: 55,
    PY_Green_POS_Cnt: 0,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 6,
    PQ_Amber_POS_Cnt: 10,
    PQ_Red_POS_Cnt: 74,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
];

export const allCardData = [
  {
    Program_Name: "APP",
    Best_Threshold_PSW: 80000,
    Better_Threshold_PSW: 50000,
    CY_Green_POS_Cnt: 9,
    CY_Amber_POS_Cnt: 0,
    CY_Red_POS_Cnt: 0,
    PY_Green_POS_Cnt: 1,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 0,
    PQ_Green_POS_Cnt: 5,
    PQ_Amber_POS_Cnt: 0,
    PQ_Red_POS_Cnt: 0,
    PPV_Green_POS_Cnt: 0,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 0,
    PPPV_Green_POS_Cnt: 0,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 0,
  },
  {
    Program_Name: "APR",
    Best_Threshold_PSW: 50000,
    Better_Threshold_PSW: 38000,
    CY_Green_POS_Cnt: 116,
    CY_Amber_POS_Cnt: 0,
    CY_Red_POS_Cnt: 9,
    PY_Green_POS_Cnt: 109,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 9,
    PQ_Green_POS_Cnt: 119,
    PQ_Amber_POS_Cnt: 0,
    PQ_Red_POS_Cnt: 7,
    PPV_Green_POS_Cnt: 76,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 26,
    PPPV_Green_POS_Cnt: 39,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 66,
  },
  {
    Program_Name: "Mono AAR",
    Best_Threshold_PSW: 38000,
    Better_Threshold_PSW: 15000,
    CY_Green_POS_Cnt: 111,
    CY_Amber_POS_Cnt: 0,
    CY_Red_POS_Cnt: 204,
    PY_Green_POS_Cnt: 81,
    PY_Amber_POS_Cnt: 0,
    PY_Red_POS_Cnt: 135,
    PQ_Green_POS_Cnt: 109,
    PQ_Amber_POS_Cnt: 0,
    PQ_Red_POS_Cnt: 192,
    PPV_Green_POS_Cnt: 37,
    PPV_Amber_POS_Cnt: 0,
    PPV_Red_POS_Cnt: 168,
    PPPV_Green_POS_Cnt: 13,
    PPPV_Amber_POS_Cnt: 0,
    PPPV_Red_POS_Cnt: 191,
  },
];

export const bento = [
  {
    CY_NSO_POS_Cnt: 111,
    CY_LFL_POS_Cnt: 402,
    CY_All_POS_Cnt: 513,
    PQ_NSO_POS_Cnt: 88,
    PQ_LFL_POS_Cnt: 399,
    PQ_All_POS_Cnt: 487,
    PY_NSO_POS_Cnt: 88,
    PY_LFL_POS_Cnt: 399,
    PY_LFL_POS_Cnt_1: 487,
    PPY_NSO_POS_Cnt: 17,
    PPY_LFL_POS_Cnt: 332,
    PPY_LFL_POS_Cnt_1: 349,
    PPPY_NSO_POS_Cnt: 17,
    PPPY_LFL_POS_Cnt: 312,
    PPPY_LFL_POS_Cnt_1: 329,
  },
];
